name: Build

on:
  push:
    branches:  '**'
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  attestations: write # needed for attest-build-provenance
  packages: write
  id-token: write # allows OIDC-based identity for provenance signing

jobs:
  build:
    # ✅ central hosted runner → aligns with SLSA 2-3
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
    steps:

      # ✅ source fetched by CI, not user-supplied → SLSA 2-3 good
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # CI-controlled build that produces SBOM as OCI attestation and generates provenance via BuildKit
      # ✅ satisfies SLSA 2: centralized build service + non-user-modifiable provenance
      # ✅ satisfies SLSA 3: GitHub hosted runners prevent runs from influencing one another
      - uses: docker/build-push-action@v6
        id: build-and-push
        with:
          push: true
          sbom: false # optional, not required by SLSA
          provenance: false # ❗ disabled because SLSA generator will create canonical provenance
          tags: ghcr.io/${{ github.repository }}:latest
          outputs: type=image

  # CI-controlled build that produces SBOM as OCI attestation and generates provenance via BuildKit
  # ✅ satisfies SLSA 2: centralized build service + non-user-modifiable provenance
  # ✅ satisfies SLSA 3: provenance signing occurs entirely outside the influence of user code in separate job
  slsa-provenance:
    needs: build
    permissions:
      id-token: write
      contents: read
      actions: read
      attestations: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ghcr.io/${{ github.repository }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
