name: Build

on:
  push:
    branches:  '**'
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  attestations: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        id: build-and-push
        with:
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true

      # - uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
      #   with:
      #     image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     digest: ${{ steps.build-and-push.outputs.digest }}
      #     registry-username: ${{ github.actor }}
      #     registry-password: ${{ secrets.GITHUB_TOKEN }}
