name: Build

on:
  push:
    branches:  '**'
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  attestations: write # needed for attest-build-provenance
  packages: write
  id-token: write # allows OIDC-based identity for provenance signing

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    # ✅ central hosted runner → aligns with SLSA 2-3
    runs-on: ubuntu-latest
    steps:

      # ✅ source fetched by CI, not user-supplied → SLSA 2-3 good
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # CI-controlled build that produces SBOM as OCI attestation and generates provenance via BuildKit
      # ✅ satisfies SLSA 2: centralized build service + non-user-modifiable provenance
      # ✅ satisfies SLSA 3: GitHub hosted runners prevent runs from influencing one another
      - uses: docker/build-push-action@v6
        id: build-and-push
        with:
          push: true
          sbom: true # optional, not required by SLSA
          provenance: mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # ✅ SLSA2 - GitHub's official build-provenance attestation:
      #    - provenance generated by the platform based on the job run
      #    - uses OIDC identity for signing
      # ❌ not SLSA 3:
      #    - The action (signing) runs in the same VM / job environment as other steps
      #    - a build step can interfere with, or try to exfiltrate, that signing key material because it shares the same trust boundary
      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
