name: Build

on:
  push:
    branches:  '**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      attestations: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          sbom: true
          provenance: mode=max
          tags: ghcr.io/lukas-havrisak-senacor/secure-pipeline-poc:latest
